# Generated by Django 3.2.8 on 2021-11-19 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BeautyMakeup', '0002_rename_beautymakeupitem_beautymakeupitem1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyMakeupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('availability', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('item_img', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeautyMakeup.beautymakeupitem'),
        ),
        migrations.DeleteModel(
            name='BeautyMakeupItem1',
        ),
    ]
