# Generated by Django 3.2.8 on 2021-12-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyMakeup', '0003_auto_20211119_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautymakeupitem',
            name='item_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
